CXX=g++
CXXFLAGS=-std=c++11 -Wall -pedantic -O3 -ffast-math -march=native -I eigen

all:
	$(CXX) $(CXXFLAGS) -o innerProduct_eigen  innerProduct_eigen.cpp
	$(CXX) $(CXXFLAGS) -o matrixMatrix_eigen  matrixMatrix_eigen.cpp
	$(CXX) $(CXXFLAGS) -o matrixVector_eigen  matrixVector_eigen.cpp